pglmm_compare(log(Brain_Mass/Body_Mass)~Nest_Building_Comp_F,
  family = "gaussian",
  data = r4.2.df,
  phy=a.r.tre5,
  REML = TRUE,
  optimizer = c("nelder-mead-nlopt", "bobyqa", "Nelder-Mead", "subplex"),
  add.obs.re = TRUE,
  verbose = FALSE,
  cpp = TRUE,
  bayes = FALSE,
  reltol = 10^-6,
  maxit = 500,
  tol.pql = 10^-6,
  maxit.pql = 200,
  marginal.summ = "mean", calc.DIC = FALSE,
  prior = "inla.default",
  prior_alpha = 0.1, prior_mu = 1,
  ML.init = FALSE, s2.init = 1, B.init = NULL)
